CREATE TABLE VEICULO (
   ID INT PRIMARY KEY, -- usar o SEQUENCE  
   nomeCliente VARCHAR,
   marcaModeloVeiculo VARCHAR, 
   anoModelo INT,
   valorVenda DOUBLE,
   CADASTRO   DATE,
);
-- JSON-> {"id":0,"nome":"CADEIRA BANCO","ativo":true,"cadastro":"2020-11-10T00:00:00.000","quantidade":12}
--INSERT INTO PRODUTO (ID, ATIVO, CADASTRO, NOME, QUANTIDADE) 
--	 VALUES (NULL, TRUE, '2020-11-01', 'COMPUTADOR DESKTOP', 10);
--INSERT INTO PRODUTO (ID, ATIVO, CADASTRO, NOME, QUANTIDADE) 
	-- VALUES (NULL, TRUE, '2020-12-11', 'MESA ESCRITÓRIO', 2);
--INSERT INTO PRODUTO (ID, ATIVO, CADASTRO, NOME, QUANTIDADE) 
	-- VALUES (NULL, TRUE, '2020-02-22', 'CADEIRA EXECUTIVA', 7);
--INSERT INTO PRODUTO (ATIVO, CADASTRO, NOME, QUANTIDADE) 
	-- VALUES (TRUE, '2022-11-14', 'MOUSE', 17);
                 